'use strict';
require('./lib/run-tmp').isolate('ptqa-ip-');

/*
 * qa/index_pins_offline.js
 *
 * work/pin-consolidation/brief.md §5 (IP-1 .. IP-11 and their planted negatives).
 * One generated pin map of index.html (functions, named regions, remainder) replaces the per-suite sha256 pins.
 *
 * Production modules under test (written AFTER this suite, tests-first):
 *   qa/lib/index-pins-core.js   pure: normalizeText, extractFunctions, buildMap, compareMaps, findDuplicates
 *   qa/tools/index-pins.js      --check | --update | --diff <git-ref>, all relative to --root <dir>
 *                               (<root>/index.html, <root>/qa/fixtures/index-pins.json); default root = the repo
 *   qa/fixtures/index-pins.json the committed map (generated by --update, never edited by hand)
 *
 * Most rows run on a small synthetic index.html (SYN) so a one-byte mutation is cheap and exact; IP-1, IP-7 and IP-11 also run
 * on the real index.html (read only). Planted negatives mutate an in-memory copy of the source text, never the real file and
 * never this test. Offline, no network; the tool rows use a private temp root (qa/lib/run-tmp.js), real Git only in IP-10.
 */

const assert = require('assert');
const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const CORE_PATH = path.join(__dirname, 'lib', 'index-pins-core.js');
const TOOL_PATH = path.join(__dirname, 'tools', 'index-pins.js');
const REAL_INDEX = path.join(ROOT, 'index.html');
const REAL_MAP = path.join(ROOT, 'qa', 'fixtures', 'index-pins.json');

let passed = 0;
let failed = 0;
const failures = [];
const pending = [];
function test(name, fn) { pending.push({ name, fn }); }

// ── plumbing ────────────────────────────────────────────────────────────────────────────────────
function lf(s) { return String(s).replace(/\r\n/g, '\n'); }
function sha256(s) { return crypto.createHash('sha256').update(s).digest('hex'); }
function countOf(hay, needle) { return needle ? hay.split(needle).length - 1 : 0; }
// Mutate exactly one occurrence of an anchor; a zero or double match is a harness defect, not a pass.
function mutate(text, anchor, replacement) {
  const n = countOf(text, anchor);
  if (n !== 1) throw new Error('harness defect: anchor occurs ' + n + ' time(s), expected exactly 1: ' + JSON.stringify(anchor));
  return text.replace(anchor, () => replacement);
}
let coreErr = null;
let coreMod = null;
try { coreMod = require(CORE_PATH); } catch (e) { coreErr = e; }
function core() {
  if (!coreMod) throw new Error('RED: qa/lib/index-pins-core.js is not loadable (' + (coreErr && coreErr.code ? coreErr.code : 'error') + ')');
  return coreMod;
}
function needTool() {
  if (!fs.existsSync(TOOL_PATH)) throw new Error('RED: qa/tools/index-pins.js does not exist');
}
function tool(args) {
  needTool();
  const r = spawnSync(process.execPath, [TOOL_PATH].concat(args), { encoding: 'utf8', windowsHide: true, maxBuffer: 64 * 1024 * 1024 });
  assert.ok(!/MODULE_NOT_FOUND/.test(String(r.stderr)), 'tool failed to load: ' + String(r.stderr).split('\n')[0]);
  return r;
}
function mkTmp(prefix) { return fs.mkdtempSync(path.join(os.tmpdir(), prefix)); }
function rmrf(p) { fs.rmSync(p, { recursive: true, force: true }); }
function W(file, content) { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, content); }
function snapshotDir(dir) {
  const out = {};
  (function walk(d) {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      if (e.name === '.git') continue;
      const p = path.join(d, e.name);
      if (e.isDirectory()) walk(p); else out[path.relative(dir, p).replace(/\\/g, '/')] = sha256(fs.readFileSync(p));
    }
  })(dir);
  return out;
}
function G(args, cwd) {
  const r = spawnSync('git', ['-c', 'user.name=ptqa', '-c', 'user.email=ptqa@example.invalid', '-c', 'commit.gpgsign=false', '-c', 'core.autocrlf=false'].concat(args), { cwd, encoding: 'utf8', windowsHide: true });
  if (r.status !== 0) throw new Error('git ' + args.join(' ') + ' failed: ' + (r.stderr || r.stdout));
  return String(r.stdout);
}

// ── synthetic index.html (SYN): two functions, three regions (two outside any function, one inside alpha) ───
const SYN = [
  '<style>',
  '/* CSS-BEGIN */ .a { color: red; }',
  '/* CSS-END */',
  '</style>',
  '<script>',
  'var TOPCONST = 1;',
  '// PF-BEGIN',
  'var PF_X = 5;',
  '// PF-END',
  'function alpha(a) {',
  '  if (a) { return 1; }',
  '  // INNER-BEGIN',
  '  var k = 2;',
  '  // INNER-END',
  '  return k;',
  '}',
  'async function beta() {',
  '  return await alpha(1);',
  '}',
  '</script>',
  ''
].join('\n');
const SYN_REGIONS = {
  css: { start: '/* CSS-BEGIN */', end: '/* CSS-END */', occurrence: 1 },
  inner: { start: '// INNER-BEGIN', end: '// INNER-END', occurrence: 1 },
  pf: { start: '// PF-BEGIN', end: '// PF-END', occurrence: 1 }
};
const DUP_SRC = 'function dup() { return 1; }\nfunction other() { return 0; }\nfunction dup() { return 2; }\nfunction dup() { return 3; }\n';

function entries(map) { return JSON.parse(JSON.stringify(map)); }
function changedNames(a, b) { const r = core().compareMaps(a, b); return r.changed.slice().sort(); }

// ── IP-1: the committed map equals the map computed from index.html (--check semantics) ────────────────────
let realMapCommitted = null;
let realIndexLf = null;
function realParts() {
  if (!realIndexLf) realIndexLf = core().normalizeText(fs.readFileSync(REAL_INDEX, 'utf8'));
  return realIndexLf;
}
test('IP-1 (positive): the committed map equals the map computed from index.html (library and --check)', () => {
  const c = core();
  assert.ok(fs.existsSync(REAL_MAP), 'RED: qa/fixtures/index-pins.json does not exist');
  realMapCommitted = JSON.parse(fs.readFileSync(REAL_MAP, 'utf8'));
  assert.strictEqual(realMapCommitted.schema, 'index-pins/v1');
  const computed = c.buildMap(realParts(), realMapCommitted.regions);
  const cmp = c.compareMaps(realMapCommitted, computed);
  assert.deepStrictEqual({ ok: cmp.ok, changed: cmp.changed, added: cmp.added, removed: cmp.removed }, { ok: true, changed: [], added: [], removed: [] });
  assert.strictEqual(realMapCommitted.fileSha256, computed.fileSha256);
  const r = tool(['--check']);   // computed once, asserted against the stored result
  assert.strictEqual(r.status, 0, '--check exit ' + r.status + ': ' + r.stdout + r.stderr);
});
test('IP-1 (negative): one changed byte inside a real function is reported by compareMaps and by --check', () => {
  const c = core();
  assert.ok(fs.existsSync(REAL_MAP), 'RED: qa/fixtures/index-pins.json does not exist');
  const committed = JSON.parse(fs.readFileSync(REAL_MAP, 'utf8'));
  const spans = c.extractFunctions(realParts());
  const target = spans.find(s => s.text.length > 40);
  const mutated = realParts().slice(0, target.start) + target.text.replace(/\{/, '{ ') + realParts().slice(target.end);
  const cmp = c.compareMaps(committed, c.buildMap(mutated, committed.regions));
  assert.strictEqual(cmp.ok, false);
  assert.deepStrictEqual(cmp.changed.filter(n => n === 'functions.' + target.key), ['functions.' + target.key]);
  // tool negative on a private copy of the real file and map (the real files are never written)
  const tmp = mkTmp('ptqa-ip1-');
  try {
    W(path.join(tmp, 'index.html'), mutated);
    W(path.join(tmp, 'qa', 'fixtures', 'index-pins.json'), fs.readFileSync(REAL_MAP, 'utf8'));
    const r = tool(['--check', '--root', tmp]);
    assert.strictEqual(r.status, 1);
    assert.ok(r.stdout.indexOf('functions.' + target.key) !== -1, 'the changed entry is listed: ' + r.stdout);
  } finally { rmrf(tmp); }
});

// ── IP-2: a 1-byte change inside a function changes exactly that function's entry ─────────────────────────
test('IP-2: a one-byte change inside a function changes exactly that function entry (and nothing else)', () => {
  const c = core();
  const base = c.buildMap(SYN, SYN_REGIONS);
  assert.deepStrictEqual(Object.keys(base.functions).sort(), ['alpha', 'beta']);
  const m = c.buildMap(mutate(SYN, '  return await alpha(1);', '  return await alpha(2);'), SYN_REGIONS);
  assert.deepStrictEqual(changedNames(base, m), ['functions.beta']);
  assert.strictEqual(m.remainderSha256, base.remainderSha256);
  assert.deepStrictEqual(m.regions, base.regions);
  // negative control: an unchanged text is not reported
  assert.deepStrictEqual(changedNames(base, c.buildMap(SYN, SYN_REGIONS)), []);
  // the suite-side helper (used by the 13 migrated suites): reports exactly the requested entries that differ
  const mutatedText = mutate(SYN, '  return await alpha(1);', '  return await alpha(2);');
  assert.deepStrictEqual(c.entryMismatches(mutatedText, base, ['functions.alpha', 'functions.beta', 'regions.pf', 'remainder']), ['functions.beta']);
  assert.deepStrictEqual(c.entryMismatches(SYN, base, ['functions.alpha', 'functions.beta', 'regions.pf', 'remainder']), []);
  assert.deepStrictEqual(c.entryMismatches(SYN, base, ['functions.nope']), ['functions.nope'], 'an entry missing from the map is reported, never passed');
  assert.deepStrictEqual(c.entryMismatches(SYN, { regions: { pf: { start: '// NOPE', end: '// NOPE2' } } }, ['functions.alpha']), ['functions.alpha'], 'an uncomputable map fails closed');
  assert.deepStrictEqual(c.entryNamesExcept(base, ['functions.alpha', 'remainder']).sort(), ['functions.beta', 'regions.css', 'regions.inner', 'regions.pf']);
});

// ── IP-3: a 1-byte change inside a named region changes exactly that region (and its enclosing function) ───
test('IP-3: a one-byte change inside a region changes that region; inside a function, also the enclosing function', () => {
  const c = core();
  const base = c.buildMap(SYN, SYN_REGIONS);
  const outside = c.buildMap(mutate(SYN, 'var PF_X = 5;', 'var PF_X = 6;'), SYN_REGIONS);
  assert.deepStrictEqual(changedNames(base, outside), ['regions.pf']);
  assert.strictEqual(outside.remainderSha256, base.remainderSha256, 'an out-of-function region is masked out of the remainder');
  const css = c.buildMap(mutate(SYN, '.a { color: red; }', '.a { color: blue; }'), SYN_REGIONS);
  assert.deepStrictEqual(changedNames(base, css), ['regions.css']);
  const inner = c.buildMap(mutate(SYN, '  var k = 2;', '  var k = 3;'), SYN_REGIONS);
  assert.deepStrictEqual(changedNames(base, inner), ['functions.alpha', 'regions.inner']);
  assert.strictEqual(inner.remainderSha256, base.remainderSha256);
  // each region digest is the digest of exactly its span (start anchor through end anchor, inclusive)
  const span = SYN.slice(SYN.indexOf('// PF-BEGIN'), SYN.indexOf('// PF-END') + '// PF-END'.length);
  assert.strictEqual(base.regions.pf.sha256, sha256(span));
});

// ── IP-4: a 1-byte change outside all functions and regions changes only remainderSha256 ────────────────
test('IP-4: a one-byte change outside every function and region changes only remainderSha256', () => {
  const c = core();
  const base = c.buildMap(SYN, SYN_REGIONS);
  const m = c.buildMap(mutate(SYN, 'var TOPCONST = 1;', 'var TOPCONST = 2;'), SYN_REGIONS);
  assert.notStrictEqual(m.remainderSha256, base.remainderSha256);
  assert.deepStrictEqual(m.functions, base.functions);
  assert.deepStrictEqual(m.regions, base.regions);
  assert.deepStrictEqual(changedNames(base, m), ['remainder']);
  assert.notStrictEqual(m.fileSha256, base.fileSha256);
});

// ── IP-5: added, deleted or renamed top-level function is reported as added / removed ─────────────────────
test('IP-5: an added, deleted or renamed top-level function is reported as added / removed', () => {
  const c = core();
  const base = c.buildMap(SYN, SYN_REGIONS);
  const added = c.compareMaps(base, c.buildMap(SYN.replace('</script>', 'function gamma() { return 9; }\n</script>'), SYN_REGIONS));
  assert.deepStrictEqual({ added: added.added, removed: added.removed, ok: added.ok }, { added: ['functions.gamma'], removed: [], ok: false });
  const deleted = c.compareMaps(base, c.buildMap(mutate(SYN, 'async function beta() {\n  return await alpha(1);\n}\n', ''), SYN_REGIONS));
  assert.deepStrictEqual({ added: deleted.added, removed: deleted.removed, ok: deleted.ok }, { added: [], removed: ['functions.beta'], ok: false });
  const renamed = c.compareMaps(base, c.buildMap(mutate(SYN, 'async function beta() {', 'async function beta2() {'), SYN_REGIONS));
  assert.deepStrictEqual({ added: renamed.added, removed: renamed.removed, ok: renamed.ok }, { added: ['functions.beta2'], removed: ['functions.beta'], ok: false });
  // the async prefix is part of the span
  assert.ok(c.extractFunctions(SYN).find(s => s.name === 'beta').text.startsWith('async function beta()'));
  // R2 helper: a "whole file except the masked functions" check also fails for an added / deleted / renamed top-level function,
  // because every function span is replaced in the remainder by a placeholder that carries its key
  const withAdded = SYN.replace('</script>', 'function gamma() { return 9; }\n</script>');
  const withDeleted = mutate(SYN, 'async function beta() {\n  return await alpha(1);\n}\n', '');
  const withRenamed = mutate(SYN, 'async function beta() {', 'async function beta2() {');
  const everythingButAlpha = c.entryNamesExcept(base, ['functions.alpha']);
  assert.ok(everythingButAlpha.indexOf('remainder') !== -1 && everythingButAlpha.indexOf('functions.alpha') === -1, 'the R2 name list keeps the remainder');
  for (const [label, text] of [['added', withAdded], ['deleted', withDeleted], ['renamed', withRenamed]]) {
    assert.notStrictEqual(c.buildMap(text, SYN_REGIONS).remainderSha256, base.remainderSha256, label + ': remainderSha256 changes');
    assert.ok(c.entryMismatches(text, base, everythingButAlpha).indexOf('remainder') !== -1, label + ': the R2 helper flags the remainder');
  }
  // an added function is NOT flagged when the check is restricted to named function entries (shows why the remainder is the carrier)
  assert.deepStrictEqual(c.entryMismatches(withAdded, base, ['functions.alpha', 'functions.beta']), []);
  // positive control: the unchanged text passes the same R2 check
  assert.deepStrictEqual(c.entryMismatches(SYN, base, everythingButAlpha), []);
  // masked function may still change freely under the R2 check (the old masked-file behaviour)
  assert.deepStrictEqual(c.entryMismatches(mutate(SYN, '  var k = 2;', '  var k = 3;'), base, c.entryNamesExcept(base, ['functions.alpha', 'regions.inner'])), []);
});

// ── IP-6: a region anchor matching 0 or > 1 times makes the map invalid (fail closed) ──────────────────────
test('IP-6: a region anchor matching zero times or more than once fails closed (throws), never a partial map', () => {
  const c = core();
  const none = Object.assign({}, SYN_REGIONS, { pf: { start: '// PF-BEGIN-MISSING', end: '// PF-END', occurrence: 1 } });
  assert.throws(() => c.buildMap(SYN, none), /pf/);
  const noEnd = Object.assign({}, SYN_REGIONS, { pf: { start: '// PF-BEGIN', end: '// PF-END-MISSING', occurrence: 1 } });
  assert.throws(() => c.buildMap(SYN, noEnd), /pf/);
  const twice = mutate(SYN, '</script>', '// PF-BEGIN\n</script>');
  assert.throws(() => c.buildMap(twice, SYN_REGIONS), /pf/);
  const twiceEnd = mutate(SYN, '</script>', '// PF-END\n</script>');
  assert.throws(() => c.buildMap(twiceEnd, SYN_REGIONS), /pf/);
  // positive control: exactly one match builds
  assert.doesNotThrow(() => c.buildMap(SYN, SYN_REGIONS));
  // a region may span whole functions (independent function entries kept, the whole span masked from the remainder) ...
  const span = { start: '// PF-BEGIN', end: '  return await alpha(1);\n}', occurrence: 1 };
  const spanning = c.buildMap(SYN, Object.assign({}, SYN_REGIONS, { pf: span }));
  assert.deepStrictEqual(Object.keys(spanning.functions).sort(), ['alpha', 'beta'], 'function entries stay independent');
  assert.deepStrictEqual(c.compareMaps(c.buildMap(SYN, SYN_REGIONS), spanning).changed.filter(n => n.indexOf('functions.') === 0), [], 'function digests unchanged by a spanning region');
  const outside = c.buildMap(mutate(SYN, 'var PF_X = 5;', 'var PF_X = 6;'), Object.assign({}, SYN_REGIONS, { pf: span }));
  assert.deepStrictEqual(changedNames(spanning, outside), ['regions.pf'], 'the spanning region masks its whole span: remainder unchanged');
  // ... but a region that starts inside a function and ends outside it (a partial overlap) fails closed
  assert.throws(() => c.buildMap(SYN, Object.assign({}, SYN_REGIONS, { pf: { start: '  var k = 2;', end: 'async function beta() {', occurrence: 1 } })), /pf.*straddles/);
  // end before start is also invalid
  const reversed = Object.assign({}, SYN_REGIONS, { pf: { start: '// PF-END', end: '// PF-BEGIN', occurrence: 1 } });
  assert.throws(() => c.buildMap(SYN, reversed), /pf/);
});

// ── IP-7: CRLF and LF forms of the file yield the identical map ─────────────────────────────────────────
test('IP-7: CRLF and LF forms yield the identical map (library and --update); skipping normalisation would not', () => {
  const c = core();
  const crlf = SYN.replace(/\n/g, '\r\n');
  assert.deepStrictEqual(c.buildMap(c.normalizeText(crlf), SYN_REGIONS), c.buildMap(c.normalizeText(SYN), SYN_REGIONS));
  assert.notDeepStrictEqual(c.buildMap(crlf, SYN_REGIONS).fileSha256, c.buildMap(SYN, SYN_REGIONS).fileSha256, 'negative control: the raw CRLF text hashes differently');
  const seed = JSON.stringify({ schema: 'index-pins/v1', regions: SYN_REGIONS }, null, 2) + '\n';
  const out = {};
  for (const form of ['lf', 'crlf']) {
    const tmp = mkTmp('ptqa-ip7-');
    try {
      W(path.join(tmp, 'index.html'), form === 'lf' ? SYN : crlf);
      W(path.join(tmp, 'qa', 'fixtures', 'index-pins.json'), seed);
      const r = tool(['--update', '--root', tmp]);
      assert.strictEqual(r.status, 0, r.stdout + r.stderr);
      out[form] = fs.readFileSync(path.join(tmp, 'qa', 'fixtures', 'index-pins.json'), 'utf8');
    } finally { rmrf(tmp); }
  }
  assert.strictEqual(out.lf, out.crlf);
  // the real file as checked out (any EOL form) and its LF form yield the same map
  const raw = fs.readFileSync(REAL_INDEX, 'utf8');
  const regs = fs.existsSync(REAL_MAP) ? JSON.parse(fs.readFileSync(REAL_MAP, 'utf8')).regions : {};
  assert.deepStrictEqual(c.buildMap(c.normalizeText(raw.replace(/\r\n/g, '\n').replace(/\n/g, '\r\n')), regs), c.buildMap(c.normalizeText(raw.replace(/\r\n/g, '\n')), regs));
});

// ── IP-8: duplicate function names are keyed deterministically (#2) and reported ───────────────────────
test('IP-8: duplicate top-level function names are keyed NAME, NAME#2, NAME#3 in file order and reported', () => {
  const c = core();
  const m = c.buildMap(DUP_SRC, {});
  assert.deepStrictEqual(Object.keys(m.functions).sort(), ['dup', 'dup#2', 'dup#3', 'other']);
  assert.strictEqual(m.functions.dup, sha256('function dup() { return 1; }'));
  assert.strictEqual(m.functions['dup#2'], sha256('function dup() { return 2; }'));
  assert.strictEqual(m.functions['dup#3'], sha256('function dup() { return 3; }'));
  assert.deepStrictEqual(c.findDuplicates(DUP_SRC), ['dup']);
  assert.deepStrictEqual(c.buildMap(DUP_SRC, {}), m, 'deterministic across calls');
  assert.deepStrictEqual(c.findDuplicates(SYN), [], 'negative control: no duplicates in SYN');
});

// ── IP-9: --update is deterministic and writes only the map file ────────────────────────────────────────
test('IP-9: --update is deterministic (two runs, identical bytes) and writes only the map file', () => {
  const tmp = mkTmp('ptqa-ip9-');
  try {
    W(path.join(tmp, 'index.html'), SYN);
    W(path.join(tmp, 'qa', 'fixtures', 'index-pins.json'), JSON.stringify({ schema: 'index-pins/v1', regions: SYN_REGIONS }, null, 2) + '\n');
    W(path.join(tmp, 'qa', 'other.txt'), 'untouched');
    const before = snapshotDir(tmp);
    const r1 = tool(['--update', '--root', tmp]);
    assert.strictEqual(r1.status, 0, r1.stdout + r1.stderr);
    const mapPath = path.join(tmp, 'qa', 'fixtures', 'index-pins.json');
    const bytes1 = fs.readFileSync(mapPath);
    const after1 = snapshotDir(tmp);
    const r2 = tool(['--update', '--root', tmp]);
    assert.strictEqual(r2.status, 0, r2.stdout + r2.stderr);
    assert.ok(bytes1.equals(fs.readFileSync(mapPath)), 'second --update rewrote different bytes');
    const changedFiles = Object.keys(after1).filter(k => before[k] !== after1[k]).sort();
    assert.deepStrictEqual(changedFiles, ['qa/fixtures/index-pins.json']);
    assert.deepStrictEqual(Object.keys(after1).sort(), Object.keys(before).sort(), 'no file created or removed');
    const written = JSON.parse(bytes1.toString('utf8'));
    assert.deepStrictEqual(Object.keys(written).sort(), ['fileSha256', 'functions', 'regions', 'remainderSha256', 'schema']);
    assert.ok(!/(timestamp|generatedAt|date)/i.test(bytes1.toString('utf8')), 'no timestamp in the map');
    assert.strictEqual(tool(['--check', '--root', tmp]).status, 0, 'a fresh map passes --check');
    // negative: a stale map fails --check
    W(path.join(tmp, 'index.html'), mutate(SYN, 'var TOPCONST = 1;', 'var TOPCONST = 2;'));
    assert.strictEqual(tool(['--check', '--root', tmp]).status, 1);
  } finally { rmrf(tmp); }
});

// ── IP-10: --diff <ref> lists exactly the changed entries with their line diff; writes nothing ───────────
test('IP-10: --diff <ref> lists exactly the changed entries and prints their line diff; it writes nothing', () => {
  needTool();
  const tmp = mkTmp('ptqa-ip10-');
  try {
    G(['init', '-q'], tmp);
    W(path.join(tmp, 'index.html'), SYN);
    W(path.join(tmp, 'qa', 'fixtures', 'index-pins.json'), JSON.stringify({ schema: 'index-pins/v1', regions: SYN_REGIONS }, null, 2) + '\n');
    assert.strictEqual(tool(['--update', '--root', tmp]).status, 0);
    G(['add', '-A'], tmp);
    G(['commit', '-q', '-m', 'base'], tmp);
    let v2 = mutate(SYN, '  return await alpha(1);', '  return await alpha(2);');
    v2 = mutate(v2, 'var PF_X = 5;', 'var PF_X = 6;');
    W(path.join(tmp, 'index.html'), v2);
    const before = snapshotDir(tmp);
    const statusBefore = G(['status', '--porcelain'], tmp);
    const r = tool(['--diff', 'HEAD', '--root', tmp]);
    assert.strictEqual(r.status, 0, r.stdout + r.stderr);
    assert.ok(r.stdout.indexOf('functions.beta') !== -1 && r.stdout.indexOf('regions.pf') !== -1, 'changed entries listed: ' + r.stdout);
    for (const unchanged of ['functions.alpha', 'regions.css', 'regions.inner', 'remainder']) assert.strictEqual(r.stdout.indexOf(unchanged), -1, unchanged + ' must not be listed');
    // exact set: every changed / added / removed entry line of the output, nothing more and nothing less
    const entryLines = out => out.split('\n').map(l => /^(changed|added|removed)\s+(\S+)\s*$/.exec(l)).filter(Boolean).map(m => m[1] + ' ' + m[2]).sort();
    const expectedEntries = ['changed functions.beta', 'changed regions.pf'];
    assert.deepStrictEqual(entryLines(r.stdout), expectedEntries, 'the listed entries are exactly the changed ones: ' + r.stdout);
    // negative control for the exact-set check itself: a spurious extra line, or a missing one, is not equal
    assert.notDeepStrictEqual(entryLines(r.stdout + 'changed  functions.alpha\n'), expectedEntries);
    assert.notDeepStrictEqual(entryLines(r.stdout.replace('changed  regions.pf', '')), expectedEntries);
    assert.ok(/^-\s+return await alpha\(1\);/m.test(r.stdout) && /^\+\s+return await alpha\(2\);/m.test(r.stdout), 'unified line diff of the changed function: ' + r.stdout);
    assert.ok(/^-var PF_X = 5;/m.test(r.stdout) && /^\+var PF_X = 6;/m.test(r.stdout), 'unified line diff of the changed region');
    assert.deepStrictEqual(snapshotDir(tmp), before, '--diff wrote nothing');
    assert.strictEqual(G(['status', '--porcelain'], tmp), statusBefore);
    // negative control: no difference -> no entries listed
    W(path.join(tmp, 'index.html'), SYN);
    const same = tool(['--diff', 'HEAD', '--root', tmp]);
    assert.strictEqual(same.status, 0);
    assert.ok(!/(functions|regions)\./.test(same.stdout) && same.stdout.indexOf('remainder') === -1, 'no entries listed for an identical file: ' + same.stdout);
  } finally { rmrf(tmp); }
});

// ── IP-11: the extractor agrees byte-for-byte with the existing extractors for every function a suite named ──
// REF_EXTRACT is a COPY of the extractor the 13 pinning suites carry today (indexOf('function NAME(') + async prefix +
// character brace matching; when the braces never close, the column-0 closing-brace rule of high1y_label / pulse_analyst_view).
// NAMED is the set of top-level functions named (quoted or as a key) anywhere in those 13 suites at baseline f40d6b6.
function refExtract(content, name, opts) {
  const o = opts || {};
  const sig = 'function ' + name + '(';
  const start = content.indexOf(sig);
  if (start === -1) return null;
  const ASYNC = 'async ';
  const realStart = (!o.dropAsync && start >= ASYNC.length && content.slice(start - ASYNC.length, start) === ASYNC) ? start - ASYNC.length : start;
  const braceStart = content.indexOf('{', start);
  if (braceStart === -1) return null;
  let depth = 0;
  for (let i = braceStart; i < content.length; i += 1) {
    if (content[i] === '{') depth += 1;
    else if (content[i] === '}') { depth -= 1; if (depth === 0) return content.slice(realStart, i + 1); }
  }
  const closeAt = content.indexOf('\n}\n', start);
  return closeAt === -1 ? null : content.slice(realStart, closeAt + 2);
}
const NAMED = ["_athAccept", "_athFetch", "_athPrefetchScan", "_athReadForView", "_crEsc", "_crFetchForScan", "_dd0FetchAnalysis", "_dd0RunCard", "_dhFxAgedLabel", "_dhLabel", "_eodBuildPacket", "_eodComputeReadiness", "_eodExportPacket", "_eodPacketToBriefing", "_eodPacketToMarkdown", "_eodPreExportWarning", "_eodReadinessLines", "_eodReconciliationLimitationText", "_eodSnapshotPackets", "_initTsCard", "_isValidScanResult", "_nlmConsistencyChecks", "_normalizePosition", "_p5BuildLocalContext", "_p5BuildPacket", "_p5CollectLocalContext", "_p5DomainFromUrl", "_p5IndexSearchResults", "_p5NormalizeUrl", "_p5PacketStatus", "_p5PreloadContext", "_p5SynthesisPayload", "_p5UsableDate", "_p5UsableTitle", "_p5ValidateItems", "_pfCashLoad", "_pfComputeHoldingsSubtotals", "_pfComputeNeedsAttention", "_pfComputePortfolioReporting", "_pfComputeReconciliation", "_pfEffectiveCostIls", "_pfEodCacheSet", "_pfEodIsStale", "_pfEodLoadCache", "_pfEodSaveCache", "_pfFxAgeWholeDays", "_pfFxLoadCache", "_pfFxRateValid", "_pfFxState", "_pfHoldingIlsValue", "_pfHoldingPl", "_pfIsFiniteNum", "_pfLiveNormalize", "_pfNormalizeHoldingEntry", "_pfReconLoad", "_pfSessionDateFor", "_ptScoreCmp", "_ptScoreDial", "_ptScoreFillHtml", "_ptScoreNorm", "_ptScoreStates", "_ptScoreText", "_renderPortfolioPanel", "_setupDisplay", "_srGroupResults", "_srHeldHtml", "_srHeldMap", "_srRenderGrouped", "_techDeriveSnap", "_techFetchBase", "_techPanelPrice", "_techRefInput", "_techSnapFor", "_ts1AgeSessions", "_ts1ExchangeLocalParts", "_ts1FetchRawSeries", "_ts1FillRow", "_ts1IsTradingSession", "_ts1ResolveMarket", "_ts1RowText", "_ts1RuleFor", "_ts1SessionCloseMinutes", "_ts1SessionCompleted", "_vscCellHtml", "analyzeChunk", "buildTechSnapshotBlock", "checkAndShowStaleBanner", "classifyTechnicalSetup", "computeHigh1yDistance", "computePctDiff", "computeRelativePerf", "computeSMA", "computeTechnicalSnapshot", "computeVolumeMetrics", "enforceScoreConsistency", "fetchAnthropicAnalysis", "fetchBatchStockData", "fetchHistoricalCandles", "fetchPerplexityContext", "fetchStockData", "findTicker", "formatStockContext", "hasVerifiedMarketData", "init", "loadHoldings", "mergeResultsByTicker", "openScanResultsOverlay", "orchestrate", "parseJSON", "parsePerplexityContext", "refreshTechPanel", "renderMainPanel", "repairJSON", "runTechScoreV1"];
function parityMismatches(spans, content, names, opts) {
  const byName = {};
  for (const s of spans) if (!(s.name in byName)) byName[s.name] = s;
  const bad = [];
  for (const n of names) {
    const ref = refExtract(content, n, opts);
    const got = byName[n] ? byName[n].text : null;
    if (ref === null || got === null || ref !== got) bad.push(n);
  }
  return bad;
}
test('IP-11: the core extractor equals the existing extractors, byte for byte, for every function a pinning suite names (planted negative: a reference without the async prefix is caught)', () => {
  const c = core();
  const content = realParts();
  assert.ok(NAMED.length > 100 && new Set(NAMED).size === NAMED.length);
  const spans = c.extractFunctions(content);
  const bad = parityMismatches(spans, content, NAMED);
  assert.deepStrictEqual(bad, [], 'functions whose core span differs from the reference extractor: ' + bad.join(', '));
  // every NAMED function is a key in the committed map
  if (fs.existsSync(REAL_MAP)) {
    const keys = JSON.parse(fs.readFileSync(REAL_MAP, 'utf8')).functions;
    assert.deepStrictEqual(NAMED.filter(n => !(n in keys)), [], 'named functions missing from the committed map');
  }
  // planted negative on the reference: the same comparison catches a divergent extractor (async functions lose their prefix)
  const asyncNames = NAMED.filter(n => content.indexOf('async function ' + n + '(') !== -1);
  assert.ok(asyncNames.length > 0, 'harness defect: no async function among the named ones');
  const bad2 = parityMismatches(spans, content, NAMED, { dropAsync: true });
  assert.deepStrictEqual(bad2.slice().sort(), asyncNames.slice().sort(), 'the dropped-async reference differs exactly on the async functions');
});

// ── IP-12: the frozen chain inputs (brief §2 / R4) are intact ──────────────────────────────────────────────
// qa/fixtures/index-pins-frozen.json holds the exact LF text the five revert chains operate on; it is written once and never
// regenerated, so its own integrity is the only thing to pin: every entry's sha256 is the digest of its text, each text is one
// complete top-level function, and the five chains and their functions are all present.
const FROZEN_PATH = path.join(ROOT, 'qa', 'fixtures', 'index-pins-frozen.json');
const FROZEN_EXPECT = {
  ath_client: ['buildTechSnapshotBlock', 'renderMainPanel'],
  ma_stack_label: ['renderMainPanel'],
  no_synthetic_score: ['_isValidScanResult', '_srGroupResults', 'analyzeChunk', 'orchestrate', 'renderMainPanel'],
  pulse_analyst_view: ['_renderPortfolioPanel', '_srGroupResults', '_srRenderGrouped', 'openScanResultsOverlay', 'renderMainPanel'],
  tech_snapshot_cache: ['renderMainPanel']
};
function frozenProblems(doc) {
  const out = [];
  if (!doc || doc.schema !== 'index-pins-frozen/v1' || !doc.chains) return ['bad schema'];
  if (JSON.stringify(Object.keys(doc.chains).sort()) !== JSON.stringify(Object.keys(FROZEN_EXPECT).sort())) out.push('chain set differs');
  for (const chain of Object.keys(FROZEN_EXPECT)) {
    const entries = (doc.chains || {})[chain] || {};
    if (JSON.stringify(Object.keys(entries).sort()) !== JSON.stringify(FROZEN_EXPECT[chain].slice().sort())) out.push(chain + ': function set differs');
    for (const fn of Object.keys(entries)) {
      const e = entries[fn];
      if (!e || typeof e.source !== 'string') { out.push(chain + '.' + fn + ': no source'); continue; }
      if (sha256(e.source) !== e.sha256) out.push(chain + '.' + fn + ': sha256 does not match the text');
      if (e.source.indexOf('\r') !== -1) out.push(chain + '.' + fn + ': not LF');
      const spans = core().extractFunctions(e.source);
      if (spans.length !== 1 || spans[0].start !== 0 || spans[0].end !== e.source.length || spans[0].name !== fn) out.push(chain + '.' + fn + ': not exactly one complete top-level function');
    }
  }
  return out;
}
test('IP-12: the frozen chain inputs are intact (sha256 per entry, LF, one complete function each, the five chains present); planted negatives are caught', () => {
  assert.ok(fs.existsSync(FROZEN_PATH), 'RED: qa/fixtures/index-pins-frozen.json does not exist');
  const doc = JSON.parse(fs.readFileSync(FROZEN_PATH, 'utf8'));
  assert.deepStrictEqual(frozenProblems(doc), []);
  // planted negatives on an in-memory copy of the fixture
  const edited = JSON.parse(JSON.stringify(doc));
  edited.chains.ma_stack_label.renderMainPanel.source += ' ';
  assert.ok(frozenProblems(edited).some(p => /sha256 does not match/.test(p)), 'an edited text is caught');
  const dropped = JSON.parse(JSON.stringify(doc));
  delete dropped.chains.no_synthetic_score.orchestrate;
  assert.ok(frozenProblems(dropped).some(p => /function set differs/.test(p)), 'a dropped function is caught');
  const crlf = JSON.parse(JSON.stringify(doc));
  crlf.chains.ath_client.renderMainPanel.source = crlf.chains.ath_client.renderMainPanel.source.replace(/\n/g, '\r\n');
  crlf.chains.ath_client.renderMainPanel.sha256 = sha256(crlf.chains.ath_client.renderMainPanel.source);
  assert.ok(frozenProblems(crlf).some(p => /not LF/.test(p)), 'a CRLF text is caught');
  const gone = JSON.parse(JSON.stringify(doc));
  delete gone.chains.tech_snapshot_cache;
  assert.ok(frozenProblems(gone).some(p => /chain set differs/.test(p)), 'a missing chain is caught');
});

// ── run ───────────────────────────────────────────────────────────────────────────────────────────
(async () => {
  for (const t of pending) {
    try { await t.fn(); passed += 1; process.stdout.write('  PASS  ' + t.name.split(':')[0] + '\n'); } catch (e) { failed += 1; failures.push(t.name.split(':')[0] + ' -- ' + (e && e.message ? e.message : String(e)).split('\n')[0]); }
  }
  if (failed > 0) {
    for (const f of failures) process.stdout.write('  FAIL  ' + f + '\n');
    process.stdout.write('\nOFFLINE VALIDATION (index pins): FAIL (' + failed + '/' + (passed + failed) + ')\n');
    process.exit(1);
  }
  process.stdout.write('  PASS  ' + passed + ' index-pin assertion(s) passed\n');
  process.exit(0);
})();
